spring:
  datasource:
    url: jdbc:mysql://localhost:3307/order_management?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: gzl123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    encoding: UTF-8
    schemas: order_management
    validate-on-migrate: true
  jackson:
    serialization:
      fail-on-empty-beans: false